### ISSUE TITLE
[rebuild] finalize and validate JSON schema

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-pycommons#15]

**Comment by simon-clematide** [comment]
Would this be the JSON schema for rebuilt text? Will all JSON schemas go into pycommons or will they be distributed in different repos?

**Comment by mromanello** [comment]
it probably makes sense to gather them all into a single place, no? I'd be in favour of moving the [text ingestion schemas](https://github.com/impresso/impresso-text-acquisition/tree/master/text_importer/schemas) here into `pycommons`, if we all agree? (cc @e-maud )

**Comment by simon-clematide** [comment]
makes sense to me

**Comment by mromanello** [comment]
A schema for the rebuilt JSON (now called "Content Item Schema") is now part of the [Impresso Schemas](https://github.com/impresso/impresso-schemas) repository.
