### ISSUE TITLE
manifest file for a collection

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-pycommons#16]
for every canonical collection we should have a manifest file on the top that just contains the paths to each file in the collection.

**Comment by mromanello** [comment]
what do you mean by "collection" in this context @simon-clematide ?

**Comment by simon-clematide** [comment]
GDL, NZZ

**Comment by mromanello** [comment]
thinking a possible format for a manifest.json file, to put e.g. at the root of our `canonical-rebuilt` file:

```json
{
    "NZZ": [
        {
            "path": "s3://canonical-rebuilt/NZZ/NZZ-1780.jsonl.bz2",
            "s3version":"a88af3eb274ff4b5d2667a3717909fdc",
            "timestamp":"Nov 22, 2018 9:07:32 AM"
        },
        {
            "path": "s3://canonical-rebuilt/NZZ/NZZ-1781.jsonl.bz2",
            "s3version":"68f7cf428e0839637fb0ce5b97c8cc53",
            "timestamp":"Nov 22, 2018 9:08:16 AM"
        },
        ...
    ],
    "GDL":[
        {
            "path": "s3://canonical-rebuilt/GDL/GDL-1798.jsonl.bz2",
            "s3version":"00ae6cbcd27e9d3c40ddcae99f6f6c20",
            "timestamp":"Nov 5, 2018 8:35:49 AM"
        },
        ...
    ]
}
``` 

What is not yet 100% clear to me are the use cases for such a manifest file. Plus, it raises the issue of which component keeps it up to date. Ideally, any component writing to a certain bucket should call a function (in `impresso-pycommons`) that generates and updates the `manifest.json` file for that bucket.

**Comment by simon-clematide** [comment]
it was more for the case of canonical representation where the lookup on s3 is a nightmare if we have millions of pages. If we stick to a zipped format later on manifests are not needed. Maybe it can be closed.
