### ISSUE TITLE
common command line tools for development

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-pycommons#17]
Hi there
@maud @mromanello  
I see some need for generally applicable scripts for development (e.g. sampling from canonical files or rebuilt files).  Would they go into pycommons, or would we have more of a separate submodule that just hosts a bunch of tools (impresso-dev-tools) and internally might rely on the pycommon library.
Opinions?

**Comment by mromanello** [comment]
Hi @simon-clematide so far some of our python modules come also with a command line interface (like the rebuild or the text import). But in general I'm not completely against a separate module (especially if we go for mixing bash scripts, python modules, java classes, etc.).

As for the rebuild module and its CLI: I'd be happy to get your feedback and desiderata for specific behaviours etc. For now it looks like this

https://github.com/impresso/impresso-pycommons/blob/52f86e0cd1f56465ba090c81e98332a00ca38b4b/impresso_commons/text/rebuilder.py#L1-L6

**NB**: the rebuild-pages command is not yet implemented. I'll document the CLI parameters, so as to make the discussion easier.
