### ISSUE TITLE
organisation of s3

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-pycommons#3]
s3 buckets:

- `original-canonical-data` what we ingest (legacy OCR)
- `processed-canonical-data` what the produce (improved OCR, NE annotations, topics, etc.)
- `processing-logs`  

In the `processed-canonical-data` bucket:
- key = `GDL-1900-01-02-a-i0001.json`, prefix = GDL/1900/01/02/a
- key = `GDL-1900-01-02-a-i0001-reuse.json`, prefix = GDL/1900/01/02/a
- key = `GDL-1900-01-02-a-p0001.json`, prefix = GDL/1900/01/02/a
- key = `GDL-1900-01-02-a-entities.json`, prefix = GDL/1900/01/02/a
- key = `NZZ-topics.json`, prefix = NZZ/

In the `processing-logs` bucket:
- for each newspaper, for each task (ingestion, NER, text-reuse detection, etc.), one file (s3 key) with a JSON document containing one record per newspaper issue + provenance information (who changed what when with which library version?)
- Update policy: if S3 has versioning, we overwrite each time the processing-log record, otherwise append to existing file

Example of processing log document (`GDL-entities.json`):

```
{
    "uuser": "unix user",
    "uploaded": "2018-05-08:17:20",
    "version": "v0.1.0",
    "records": [
        "GDL-1900-01-02-a",
        "GDL-1900-01-03-a"
    ]
}
```

**Comment by mromanello** [comment]
now that I was thinking about implementing this, another use case came to my mind:

- I split the text importing of e.g. GDL into 3 batches
- I upload separately each bash to S3 as soon as it's ready

I believe the example above does not cover it. But this:

```
{
    "logs": [{
      "uuser": "unix user",
      "uploaded": "2018-05-08:17:20",
      "version": "v0.1.0",
      "records": [
          "GDL-1900-01-02-a",
          "GDL-1900-01-03-a"
      ]
   }]
}
```
where each log represents a separate operation (possibly incremental).

What do you think?

**Comment by e-maud** [comment]
Suggestion for the organization of `processed-canonical-data`:

- each type of processing has its own prefix, e.g. `ne_mention`, `topics`, `ocr_asses`, etc.
- under this, classical hierarchy `journal/` and then archives at year granularity level (tbc with experience)

```
processed-canonical-data/
		├── ne_mention/
		│   ├── GDL/			
		│   │    ├── GDL-1975_mentions.jsonl.bz2
		│   │    ├── GDL-1976_mentions.jsonl.bz2
		│   │    └── etc.
		│   ├── JDG/    
                ├── topics/
                │   ├── GDL/			
		│   │    ├── GDL-1975_topics.jsonl.bz2
		│   │    └── etc.
		│   ├── JDG/    
                ├── ocr_assess/
```

**Comment by simon-clematide** [comment]
maybe not `ocr_asses` but `ocr_assess`

**Comment by simon-clematide** [comment]
Renamed the topic model canonical file names a bit. It makes sense to me, to name the jsonl files as closely as possible to the name of the schema that defines their content. Additionally, multiplying the tm000 subdirectory information in the filenames is not necessary (as I thought before), because the information is also present in the topic description files.

**Comment by mromanello** [comment]
After several attempts to find the best way of "packaging" the canonical data for storage on s3 and further distributed processing, it turns out this is the best one:
- all issue JSON packaged by newspaper/year into a single archive
- all pages for a given issue packaged in a separate archive.

This format improves drastically the performances especially when running the rebuild process.

```
s3://original-canonical-data/
		├── IMP/
                │   ├── IMP-1881-issues.jsonl.bz2
                │   ├── IMP-1882-issues.jsonl.bz2
		│   ├── IMP-1881/			
		│   │    ├── IMP-1881-01-01-a-pages.jsonl.bz2
		│   │    ├── IMP-1881-01-04-a-pages.jsonl.bz2
```

For the June release, all canonical data will be re-ingested in this format. @simon-clematide could you please put the NZZ canonical data in `s3://original-canonical-data/` in this way ? For the alpha release I was using a separate bucket `s3://original-canonical-compressed/I` (as I was still trying things out).
