### ISSUE TITLE
[rebuild] fields to add

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-pycommons#5]
the following fields should be added to the JSON produced by the rebuild function:

- [ ] add s3 version of canonical issue.json
- [x] adding `item type`, i.e. article `ar`, advert `ad`, etc. if available (`tp` in issue.json)
- ~~[ ] adding `doc type`, i.e. page `p` or article `a` => it is actually in the id, therefore not necessary?~~
- [x] `lang`: iso 639-1 code + key shortening 'lg'
- [ ] properties names need to be shortened (region => r, coords => c, etc.)
- [x] `line_breaks` field (name `lb`), pointing via offsets to positions in the `text` field

**Comment by mromanello** [comment]
@danieleguido following up on the discussion we had yesterday wrt to line breaks (in the text to be displayed to the user) @maud and I came up with this solution:

- line break information will be stored in the JSON passed Solr, and accessible (but not indexed) in a similar way to the `regions` field
- each line break points, in a stand-off fashion, to positions in the text contained in the `text` field

Essentially, to render the text for display you'll have to insert `<br/>` elements in the positions specified in the line break field.

Does this sound reasonable/feasible to you? (hope so 😜)

**Comment by danieleguido** [comment]
Thanks @mromanello, it is totally feasible, cut at offset then join ;)

**Comment by mromanello** [comment]
Ok, great to know this would work for you!

> but... am I allowed to access the json file directly ?

From an architectural point of you, it is too fragile to have you (i.e. your code) reading in data from too many sources of information (s3, DB, Solr). We do think it's best to limit it to DB + Solr and I'm happy to put any information you may need into either the DB or Solr.

>  I would do the same I do for the regions, with a import script to put the offsets in neo4j ... 🙊

I'm not at all worried about what you do on "your side" with the data you need from DB/Solr. If you need to replicate (some of) them in neo4j, that's fine by us, as you will take care of the synchronization mechanism.

What we are worried about is the synchronization problems we are most certainly going to have if you read (possibly concurrent) information from s3 + DB + Solr. 

Is there any information that you need on your side and that is not currently in the DB or Solr? If so, pleased add it to the [list above](https://github.com/impresso/impresso-pycommons/issues/5#issue-326476515) so that I can make sure you'll find it in DB/Solr.

**Comment by danieleguido** [comment]
I'll keep track of the version id ;-)
But it's ok, you can store the `lb` property in solr. I still have questions though, probably a stupid one: is text split according to regions? can we add a `region_break` `rb` in the text?

**Comment by e-maud** [comment]
@danieleguido : we will put all what you need in SOLR and/or DB and would prefer that you avoid taking information from S3, for the reason mentioned earlier by Matteo. However, if you have good reasons to do so, we are happy to consider them!
In general, it would be helpful if you could tell us exactly what you need (that you are aware of so far), so that we can discuss together what's the most suitable place to provide it and anticipate work. I therefore suggest that you list your needs, Matteo and I think/react on this, and we take final decisions in Sept in Lux all together. What do you think?
Overall, there is room to mess up everything if we do not coordinate properly, and the more time passes the more difficult it will be to refactor code.

**Comment by danieleguido** [comment]
Hi @e-maud,
there are no good reason to use S3 directly, I just needed to get the regions of the articles - in order to complete the API for the search - and at that time they were only available on S3.

I'd rather prefer SOLr to handle text related contents since it is the only place where we can get the full text of articles.

Concerning the wishlist :

1. I'd love to have page breaking points as a flattened array, e.g. `page_offsets: [135, 285, 500]`: in this case, I expect the article text to have 4 pages: 

    - `0 to 135`, 
    - `135 to 285`, 
    - `285 to 500`, 
    - `500 to <eot>`

1. then, region offsets, e.g. `region_offsets: [60, 135, 180, 285 ... ]`  - this list should include the `page_offsets`

1. finally, line offsets like `line_offsets: [32, 60, 90, 110, 135 ... ]` - this list should include both the `page_offsets` and the `region_offsets`

Does this make sense :)?

**Comment by mromanello** [comment]
this works for me. I just have to rewrite accordingly what I'd implemented yesterday. 

@e-maud does this format cause you any troubles with your Solr ingestion? If not, I'll work on it tomorrow.

**Comment by e-maud** [comment]
@danieleguido @mromanello 
Thanks Daniele for these specifications, this is more than useful. Re SOLR, these infos will be stored as they are in dedicated fields which will not be analyzed, so I don't mind any format. 
Just a clarification on naming: theoretically everything is a region of an image (a token, a line, a paragraph, etc.). What you mean by `region` is paragraph, right?

**Comment by mromanello** [comment]
> What you mean by region is paragraph, right?

actually in my rebuilt JSON (and thus in Solr) region coordinates are only for tokens, aren't they?

**Comment by danieleguido** [comment]
Perfect @mromanello 👍 and thanks @e-maud 🥇 
Well, each `region` in our neo4j model is actually the concatenation of all `r.c` coordinates for the same `pOf` for the same page, so we get those blue nice rectangles :). For text, I imagine the same mechanism but related to text offsets instead.

Here is my reference for the regions coordinates for the images, the data model could probably be outdated):

```json
{
   "cc": true,
   "r": [
      {
         "c": [
            122,
            50,
            837,
            280
         ],
         "p": [ ... ],
         "n": "1",
         "pOf": "GDL-1811-11-22-a-i0001"
      },

```

We should have the same with text offsets, and yes, we probably should add `paragraphs_offsets` to Solr ...

**Comment by mromanello** [comment]
I can easily store all these offsets from within the same `for` loop. So we just need to decide 😜What do you think @e-maud ? Also pinging @simon-clematide

**Comment by e-maud** [comment]
Yes regions in the current rebuilt are only for tokens, I agree. I somehow had in mind that Daniele wanted the paragraphs and confused things, sorry about that.

It actually depends on the visualisation needs: 
Which segmentation levels 1. do users need to see 2. would be useful for us to see ?

If segmentation at page levels, we cannot show more than paragraphs.
If segmentation at article level, better to display article regions than their (embedded) paragraphs.

@danieleguido : currently, do you manage to reproduce article segmentation from the token  regions that compose them? (or do you do it at all?)

**Comment by e-maud** [comment]
@mromanello : what kind of regions are there in the canonical-original, everything (token, paragraphs)?
(I know I could have a look, but the answer will be quicker from you :) )

**Comment by danieleguido** [comment]
In the layout the article page (in sense of UI page) looks like a scrap book: we render all article regions jpg one after the other; each image has its text on the right. With th line break and paragraph break, we can have a faithful transcription, line by line. That is, I'll put `<p>`html tags on paragraph offsets, and `<br>` on line break.

@e-maud Yes, I do reproduce the segmentation for the top level regions, e.g. for the article: `GDL-1954-06-29-a-i0084` I have 3 regions represented as flattened array of 12 values (each coord has 4 value) for the page `GDL-1954-06-29-a-p0005` this is how the API looks like:
```json
"regions": Array[12][
          1533,
          5179,
          625,
          300,
          1533,
          5479,
          625,
          517,
          1538,
          6000,
          621,
          750
        ],
        "article_uid": "GDL-1954-06-29-a-i0084",
        "page_uid": "GDL-1954-06-29-a-p0005"
```

**Comment by mromanello** [comment]
with coordinates: page regions (e.g. column), lines and tokens. Paragraph offsets can be derived too if needed.

**Comment by e-maud** [comment]
@danieleguido Thanks again for these infos, that's all good to know !

So questions are:
- providing middle and top level regions to Daniele vs. Daniele re-compute them
- if we provide these regions, how and where: certainly same as for token regions.

My opinion would be if smthg is already available on our side, there is no point to recalculate it downstream (unless for space/info heavyness reasons) ?

UI is not necessarily the only usage for this layout info: Would any text-mining stuff benefit from it? Possible, tbd. If yes, then it might be better to keep them in the rebuilt

**Comment by simon-clematide** [comment]
I fully agree that text-level regions (paragraphs) should have coordinates as well.
