### ISSUE TITLE
`IssueDir` cannot be pickled

### ISSUE THREAD

**Issue by mromanello** [impresso/impresso-pycommons#64]
The namedtuple `impresso_commons.path.path_fs.IssueDir` cannot be pickled (it's heavily used by `impresso text-importer` module).

This constitutes a problem when running the `text-importer` in synchronous scheduling mode (useful when debugging). Running the importer at scale (i.e. with dask's distributed scheduling) is not affected probably because it uses `cloudpickle` instead of `pickle` to handle the pickling of objects.

To reproduce the issue:

```python

import pickle
from impresso_commons.path.path_fs import IssueDir

with open('test.pickle', 'w') as file:
    pickle.dump(IssueDir, file)
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-4-65af4009d0a0> in <module>
      1 with open('test.pickle', 'w') as file:
----> 2     pickle.dump(IssueDir, file)
      3

PicklingError: Can't pickle <class 'impresso_commons.path.path_fs.IssueDirectory'>: attribute lookup IssueDirectory on text_importer.importers.core failed
```

**Comment by e-maud** [comment]
Arg, from what I found it is related to namedtuple:
https://stackoverflow.com/questions/16377215/how-to-pickle-a-namedtuple-instance-correctly

**Comment by mromanello** [comment]
@e-maud yes, it turned out it was an issue with naming: the namedtuple class needs to have the same name as the variable is assigned to (!).
